language: node_js
script:
- make archive
deploy:
  provider: releases
  api_key:
    secure: tpnBaWzt7VQwygf61Y/lbm54bpC9DPFX64QriH8J5dw84BheqLR2GEBjXOcwcehLErViJROL89P8SlIPR4xQYDDXtbOm1jfyMz8M4ecWXO1uVosG6+hkGb24H+wQuw+bAU9TNfNB0uwVGVjv9ZaUfQmLSiGKtG+DOzZ0rFb8QaQ=
  file: build/PHPcURLCodeGenerator.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-PHPcURLCodeGenerator
